import { useState } from "react";
import { Cpu, ShieldAlert, Sparkles, CheckCircle, RefreshCw, AlertCircle } from "lucide-react";

interface PresetSample {
  title: string;
  type: "Human" | "AI" | "Hybrid";
  text: string;
}

const PRESETS: PresetSample[] = [
  {
    title: "100% Authentic Human Outline (Resume draft)",
    type: "Human",
    text: "Motivated Bachelor of Science in Information Technology (BSIT) candidate at Pamantasan ng Lungsod ng Pasig. Expected to graduate in June 2027. Passionate about software development, cybersecurity, and hands-on React.js engineering with a deep hunger to learn."
  },
  {
    title: "Typical AI Marketing Output (ChatGPT-v4)",
    type: "AI",
    text: "In today's fast-paced digital ecosystem, it is absolutely paramount to synergize advanced software paradigms. Furthermore, AI-driven architectures foster disruptive methodologies that enable agile orchestration across hyper-scalable data lakes."
  },
  {
    title: "Mixed Hybrid Copy (AI-Edited Draft)",
    type: "Hybrid",
    text: "Here is the layout for my cybersecurity lab. I ran a standard Nmap scan on the target system to identify open ports, but then utilized custom AI automation scripts to categorize potential CVE vulnerabilities in order to streamline mitigation workflows."
  }
];

export default function AYDetectorSimulator() {
  const [inputText, setInputText] = useState(PRESETS[0].text);
  const [scanning, setScanning] = useState(false);
  const [scanResult, setScanResult] = useState<{
    score: number; // 0-100 (AI percentage)
    perplexity: number;
    burstiness: number;
    watermark: "NOT_DETECTED" | "PROBABLE" | "CONFIRMED";
    verdict: string;
    details: string;
  } | null>(null);

  const handleSelectPreset = (p: PresetSample) => {
    setInputText(p.text);
    setScanResult(null);
  };

  const runDetection = () => {
    if (!inputText.trim()) return;
    setScanning(true);
    setScanResult(null);

    // Simulated scan timer
    setTimeout(() => {
      let score = 50;
      let perplexity = 82;
      let burstiness = 74;
      let watermark: "NOT_DETECTED" | "PROBABLE" | "CONFIRMED" = "NOT_DETECTED";
      let verdict = "HYBRID / MIXED CONTENT";
      let details = "The text contains a blend of authentic, irregular human sentence patterns alongside standard corporate-style transitions commonly generated by large language models.";

      const lower = inputText.toLowerCase();

      // Simple heuristic simulator for authentic feel
      if (lower.includes("paramount") || lower.includes("synergize") || lower.includes("disruptive") || lower.includes("furthermore")) {
        score = 94;
        perplexity = 22;
        burstiness = 15;
        watermark = "CONFIRMED";
        verdict = "HIGHLY PROBABLE AI GENERATION";
        details = "Extremely low complexity, repetitive transitions, and the presence of predictive AI text-watermarking markers suggest this text was synthesized by an LLM (such as ChatGPT, Claude, or Gemini).";
      } else if (lower.includes("motivated") || lower.includes("consistent president's") || lower.includes("expected to graduate")) {
        score = 6;
        perplexity = 138;
        burstiness = 115;
        watermark = "NOT_DETECTED";
        verdict = "HUMAN AUTHORSHIP DETECTED";
        details = "High sentence structure variation (burstiness) and unique vocabulary distribution (perplexity). Analysis indicates an extremely low probability of generative model interference.";
      } else {
        // Fallback default mock
        score = Math.floor(Math.random() * 40) + 30; // 30-70%
      }

      setScanResult({ score, perplexity, burstiness, watermark, verdict, details });
      setScanning(false);
    }, 2200);
  };

  return (
    <div className="w-full border border-zinc-800 bg-cyber-dark/80 rounded-lg p-4 sm:p-5 font-sans relative overflow-hidden group">
      {/* Visual scanning line */}
      {scanning && (
        <div className="absolute inset-x-0 h-[2px] bg-cyber-yellow box-glow-yellow animate-scanline z-20" />
      )}

      {/* Header */}
      <div className="flex items-center justify-between border-b border-zinc-800 pb-3 mb-4">
        <div className="flex items-center gap-2">
          <Cpu size={16} className="text-cyber-yellow animate-pulse" />
          <span className="font-mono text-xs text-cyber-yellow tracking-wider font-semibold uppercase">AY.ai // Multimedia AI Content Auditor</span>
        </div>
        <div className="flex items-center gap-1">
          <span className="h-1.5 w-1.5 rounded-full bg-cyber-yellow animate-ping" />
          <span className="text-[10px] font-mono text-zinc-500 uppercase">ENGINE_V2.0_READY</span>
        </div>
      </div>

      {/* Selector presets */}
      <div className="mb-4 space-y-1.5">
        <label className="block text-[10px] font-mono uppercase tracking-widest text-zinc-500">Preset Training Matrices</label>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-2">
          {PRESETS.map((p, idx) => (
            <button
              key={idx}
              onClick={() => handleSelectPreset(p)}
              className={`text-left text-[11px] p-2 rounded border font-mono transition-all duration-200 cursor-pointer ${
                inputText === p.text
                  ? "border-cyber-yellow bg-cyber-yellow/5 text-cyber-yellow font-bold"
                  : "border-zinc-800 bg-cyber-gray/45 text-zinc-400 hover:border-zinc-700 hover:text-zinc-200"
              }`}
            >
              <div className="flex items-center gap-1 mb-0.5">
                <span className={`h-1.5 w-1.5 rounded-full ${
                  p.type === "Human" ? "bg-emerald-500" : p.type === "AI" ? "bg-red-500" : "bg-cyber-yellow"
                }`} />
                <span className="uppercase text-[9px] tracking-wider">{p.type}</span>
              </div>
              <p className="truncate">{p.title}</p>
            </button>
          ))}
        </div>
      </div>

      {/* Inputs */}
      <div className="space-y-1.5 mb-4">
        <div className="flex justify-between items-center text-[10px] font-mono uppercase text-zinc-500">
          <label>Audit Buffer Input (Text Payload)</label>
          <span>{inputText.length} CHARS</span>
        </div>
        <textarea
          value={inputText}
          onChange={(e) => setInputText(e.target.value)}
          placeholder="Paste content here to audit..."
          disabled={scanning}
          className="w-full h-24 p-3 rounded bg-cyber-gray/80 border border-zinc-800 focus:border-cyber-yellow/40 focus:ring-1 focus:ring-cyber-yellow/20 outline-none text-xs text-white font-mono leading-relaxed resize-none disabled:opacity-50"
        />
      </div>

      {/* Action Trigger */}
      <div className="flex justify-end mb-4">
        <button
          onClick={runDetection}
          disabled={scanning || !inputText.trim()}
          className="flex items-center gap-2 px-4 py-2 border border-cyber-yellow bg-cyber-yellow text-black font-semibold font-sans text-xs rounded hover:bg-transparent hover:text-cyber-yellow transition-all duration-300 disabled:opacity-50 disabled:hover:bg-cyber-yellow disabled:hover:text-black cursor-pointer"
        >
          {scanning ? (
            <>
              <RefreshCw size={13} className="animate-spin" />
              <span>DECRYPTING PHRASE PARADIGMS...</span>
            </>
          ) : (
            <>
              <Cpu size={13} />
              <span>AUDIT TEXT PAYLOAD</span>
            </>
          )}
        </button>
      </div>

      {/* Results HUD */}
      {scanResult && !scanning && (
        <div className="border border-zinc-800 bg-cyber-gray/50 rounded-lg p-3 sm:p-4 space-y-4 font-mono crt-flicker">
          <div className="flex items-center gap-2 border-b border-zinc-800/60 pb-2">
            <ShieldAlert size={14} className="text-cyber-yellow" />
            <span className="text-[10px] uppercase font-bold tracking-wider text-cyber-yellow">Analysis Audit Report</span>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-12 gap-4 items-center">
            {/* Meter */}
            <div className="md:col-span-5 flex flex-col items-center justify-center p-3 border border-zinc-800 bg-cyber-dark/60 rounded">
              <span className="text-[10px] text-zinc-500 uppercase tracking-wider mb-2">Confidence Scale</span>
              <div className="relative flex items-center justify-center h-20 w-20">
                {/* SVG Dial */}
                <svg className="w-full h-full transform -rotate-90">
                  <circle cx="40" cy="40" r="34" stroke="rgba(255,255,255,0.05)" strokeWidth="6" fill="transparent" />
                  <circle
                    cx="40"
                    cy="40"
                    r="34"
                    stroke={scanResult.score > 50 ? "#EF4444" : scanResult.score > 20 ? "#FFE600" : "#10B981"}
                    strokeWidth="6"
                    fill="transparent"
                    strokeDasharray={2 * Math.PI * 34}
                    strokeDashoffset={2 * Math.PI * 34 * (1 - scanResult.score / 100)}
                    className="transition-all duration-1000"
                  />
                </svg>
                <div className="absolute inset-0 flex flex-col items-center justify-center">
                  <span className="text-lg font-bold text-white leading-none">{scanResult.score}%</span>
                  <span className="text-[8px] text-zinc-500 uppercase mt-0.5">AI SCORE</span>
                </div>
              </div>
              <span className={`text-[10px] font-bold mt-3 px-2 py-0.5 rounded ${
                scanResult.score > 50 ? "bg-red-500/15 text-red-400 border border-red-500/20" : 
                scanResult.score > 20 ? "bg-cyber-yellow/15 text-cyber-yellow border border-cyber-yellow/20" : 
                "bg-emerald-500/15 text-emerald-400 border border-emerald-500/20"
              }`}>
                {scanResult.verdict}
              </span>
            </div>

            {/* Explanations & Telemetrics */}
            <div className="md:col-span-7 space-y-3 text-xs">
              <div className="space-y-1">
                <p className="text-[10px] text-zinc-500 uppercase font-semibold">Diagnostic Output</p>
                <p className="text-zinc-300 leading-relaxed text-[11px]">{scanResult.details}</p>
              </div>

              {/* Sub-Metrics Grid */}
              <div className="grid grid-cols-3 gap-2 pt-1 border-t border-zinc-800/60 text-[10px] text-zinc-400">
                <div className="p-1.5 rounded border border-zinc-800 bg-cyber-dark/40">
                  <p className="text-zinc-500 uppercase text-[8px]">Perplexity</p>
                  <p className="font-bold text-white text-xs mt-0.5">{scanResult.perplexity}</p>
                </div>
                <div className="p-1.5 rounded border border-zinc-800 bg-cyber-dark/40">
                  <p className="text-zinc-500 uppercase text-[8px]">Burstiness</p>
                  <p className="font-bold text-white text-xs mt-0.5">{scanResult.burstiness}</p>
                </div>
                <div className="p-1.5 rounded border border-zinc-800 bg-cyber-dark/40">
                  <p className="text-zinc-500 uppercase text-[8px]">Watermark</p>
                  <p className={`font-bold text-xs mt-0.5 ${
                    scanResult.watermark === "CONFIRMED" ? "text-red-400" :
                    scanResult.watermark === "PROBABLE" ? "text-cyber-yellow" : "text-emerald-400"
                  }`}>{scanResult.watermark}</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* No Scan placeholder */}
      {!scanResult && !scanning && (
        <div className="flex flex-col items-center justify-center p-8 border border-dashed border-zinc-800 rounded-lg text-zinc-500 bg-cyber-gray/10">
          <AlertCircle size={20} className="text-zinc-700 mb-2 animate-bounce" />
          <p className="font-mono text-[10px] uppercase text-zinc-600">Audit system inactive. Select a preset matrix and audit above.</p>
        </div>
      )}
    </div>
  );
}
